/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'figer' at '9/8/16 11:41 AM' with Gradle 2.8
 *
 * @author figer, @date 9/8/16 11:41 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
